[知乎](https://zhuanlan.zhihu.com/p/21580949)

<div><img src="./img/1001.png", width=500>

In [2]:
import numpy as np
X = np.array([[-1, -2], [-1, 0], [0, 0], [2, 1], [0, 1]], dtype = float )
X

array([[-1., -2.],
       [-1.,  0.],
       [ 0.,  0.],
       [ 2.,  1.],
       [ 0.,  1.]])

In [3]:
m, n = X.shape
m, n

(5, 2)

In [4]:
X.T

array([[-1., -1.,  0.,  2.,  0.],
       [-2.,  0.,  0.,  1.,  1.]])

In [5]:
C = X.T.dot(X)/m
C

array([[1.2, 0.8],
       [0.8, 1.2]])

<div><img src="./img/1002.png", width=500>

In [6]:
lam, c = np.linalg.eig(C)
lam, c

(array([2. , 0.4]), array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [7]:
1/(2**0.5)

0.7071067811865475

In [9]:
c

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [8]:
P = c.T
P

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

<div><img src="./img/1003.png", width=600>

In [10]:
np.round(P.dot(C).dot(P.T), decimals = 2) # 保留两位小数

array([[ 2. , -0. ],
       [-0. ,  0.4]])

In [11]:
Y = P[0].dot(X.T)
np.round(Y, decimals = 4)

array([-2.1213, -0.7071,  0.    ,  2.1213,  0.7071])

AMAZING!